sudo: false
language: node_js
node_js:
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib
os:
- osx
- linux
before_deploy:
- ARCHIVE_NAME="prebuild-$TRAVIS_OS_NAME-`uname -m`.tar"
- npm run prebuild
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ARCH=ia32 npm run prebuild; fi
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  overwrite: true
  skip_cleanup: true
  name: "prebuild-2.1.1"
  on:
    all_branches: true
  api_key:
    secure: "CdqIG/l3q6oeaJIOSQNhdYR8t+cQPf3Tlw6D85+xsWdKQ9oUk3NeC7kbNpDGg5NSoEjOkkcmDgHTszgt7mSEjcdyvhBalYIa9Yu5ssXRskY7U78SxoqkYgKZ3nO18ruXoS/dy01KthFgHUo4+OQQXn2C3L+BUr489Z7hfjVaKPAbl0sbiKXxmu5t4/CcjrQpcMm6lBF082EkPTGsv2hqT36d2bb1eDx9yEVTYPXlN6p/c6ybPzvhuF4fxEXRxipggF9OlWtM/LuBdprxNVTMwZyd6C5WpWonEK6SKwRtXnzhWnFy4ixBplmrHbrBkCDvsuIGAbg2EylB5Ao7lCeBi0SdGmCtS9jNh1L0PKBV1Lz7SfmVGYNxldD2XjbPAHcvlAqJpzVES2XSZFjK/rY4WDtwvmPIEmBpFfRYt+CBnQCsVABMQpdmHHLmSHmnyE7kZuIgB7gtMQSTVXJNYwf0qsCGHDUIhfmhM2LEOgaJ/6vpDoaCX+FsL/7tfFmpBsh6vc+GDW217JWVlXZlKn4YqxoZs/51aWIiMv4eJxB7FgPKzkvc/bV5/xBtNZczcaSzHq9HArCUGersa0otmLNikDlQu8p/EO15dE6o0mfOcoHzhHfffgVO7oMVcxd7aXplUwGuFuaUWHhksawaiRLCu6Yl4/K8v/llYibYPJhmliQ="
